data_ingestion:
  bucket_name: "mlops-project-2-nima"
  bucket_file_names:
    - 'anime.csv'
    - 'anime_with_synopsis.csv'
    - 'animelist.csv'
  row_limit : 1200
  threshold : 10

model_training:
  embedding_size: 32
  loss: binary_crossentropy
  learning_rate: 0.001
  metrics: ['mse','mae']
  batch_size : 1024
  patience : 3
  verbose : 1
  force_training : True
  epochs : 10

suggestion:
  n : 20
  genres_weight : 0.3
  user_weight : 0.7
  content_weight : 0.3
  min_rating : 1
  max_rating : 10
  inf_epoch : 300
  inf_lr_rate : 0.01
  n_similar_users: 30 
  diversity_weight: 0.2
  



